[Simulation]

[129026]
cog = [0.30, 0.12]          # radians
sog = [1.31, 2.40]          # m/s
cog_reference = [1, 1]      # 0=true, 1=magnetic

[130312]
actual_temperature = [300, 213.2, 233.89]   # K
set_temperature = [0, 0, 1]                 # K
source = [0, 0, 1]
instance = [0, 0, 1]
